<?php
/**
 * @package     Dadolun_SibContactSync
 * @copyright   Copyright (c) 2023 Dadolun (https://www.dadolun.com)
 * @license    This code is licensed under MIT license (see LICENSE for details)
 */

use \Dadolun\SibContactSync\Block\Adminhtml\Config\SyncContacts;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var SyncContacts $block */
/** @var SecureHtmlRenderer $secureRenderer */
?>

<?php
$ajaxUrl = $block->escapeJs($block->getAjaxUrl());
$errorMessage = $block->escapeJs($block->escapeHtml(__('Error during contact sync. Please retry.')));

$scriptString = <<<script
require(['jquery'], function($) {

//<![CDATA[
    function syncContacts() {

        new Ajax.Request('{$ajaxUrl}', {
            onSuccess: function(response) {
                var syncMessage = $('#sync_contact_result');
                var result = '{$errorMessage}';
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        result = response.message;
                    }
                    if (response.valid == 1) {
                        syncMessage.removeClass('hidden').removeClass('admin__field-error').addClass('note');
                        syncMessage.css({color:'green'});
                    } else {
                        syncMessage.removeClass('hidden').addClass('admin__field-error');
                    }
                } catch (e) {
                    syncMessage.removeClass('hidden').removeClass('admin__field-error');
                }
                syncMessage.text(result);
            }
        });
    }

    window.syncContacts = syncContacts;
//]]>

});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>

<div class="actions actions-validate-vat">
    <p class="admin__field-error hidden" id="sync_contact_result"></p>
    <button class="action-validate-vat" type="button" id="<?= /* @noEscape */ $block->getHtmlId() ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
<?= /* @noEscape */ $secureRenderer->renderTag('style', [], '#sync_contact_result {margin-bottom: 10px;}', false); ?>
<?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
    'onclick',
    'syncContacts();event.preventDefault();',
    '#' . /* @noEscape */ $block->getHtmlId()
); ?>
